### ISSUE TITLE
Connector does not filter field value for current entity

### ISSUE THREAD

**Issue by PagnoDunadan** [2sic/eav-item-dialog-angular#140]
## I'm submitting a ...

[x] action / task

## ...about

[x] edit experience / UI

## Task / Action Summary
Connector does not filter field value for current entity which results in fields having wrong value when multiple entities are in the same form. e.g. Entity has a field Title and on language change reads it properly, but Presentation doesn't have field Title and connector returns undefined value in the first Entity.

**Comment by iJungleboy** [comment]
Just for my info so I can communicate it properly - was this the multi-language switch issue?
