### ISSUE TITLE
Add ngrx store for one-way data-flow, but don't update values from UI yet

### ISSUE THREAD

**Issue by iJungleboy** [2sic/eav-item-dialog-angular#2]
## I'm submitting a ... 
[x] action / task

## ...about   
[x] edit experience / UI  

## Task / Action Summary

Integrate NGRX Store as the central store for the UI form. Basically the entire state should be in the store, incl.:

1. `items` current items being edited 
1. `contentTypes` content-type definitions (what fields exist, their configuration), etc.
1. `config` ui configuration like current languages, appid, etc.
1. _other things_ we haven't thought about

Important: this is one of the first steps, so it shouldn't be a full implementation _yet_. Don't worry about creating one-way data flow & update reducers etc. yet, just make sure the store is there and can provide most of these data types. 

Important: this is just the "create store" task - the internal data structures / formats don't have to be handled yet, that's a separate task.

## Steps to implement
* [x] install ngrx store
* [x] structure the store so it can provide the above mentioned data

**Comment by antegadzo** [comment]
Ngrx store installed
