### ISSUE TITLE
Language switcher bottom border, Icon picker spacing, Edit form bottom padding

### ISSUE THREAD

**Issue by PagnoDunadan** [2sic/eav-item-dialog-angular#43]
## I'm submitting a ...

[x] task

## ...about

[x] UI

## Steps to implement

* [x] Language switcher: remove bottom border radius
* [x] Icon picker: add space between icons and text
* [x] Edit form: remove extra padding after final card

**Comment by iJungleboy** [comment]
@PagnoDunadan BTW: if you think the task is completed, feel free to close them.
