### ISSUE TITLE
Split header from Language switcher - to it's shown even without multi-language

### ISSUE THREAD

**Issue by PagnoDunadan** [2sic/eav-item-dialog-angular#46]
## I'm submitting a ...

[x] task

## ...about

[x] UI

## Steps to implement

* [x] Show language switcher even without languages activated in app

**Comment by iJungleboy** [comment]
Just to understand this -why would it need language switchers if no language is activated?

**Comment by PagnoDunadan** [comment]
Entire header is inside language switcher. We will have to separate them.

With languages:
![2019-01-24 10_40_21-window](https://user-images.githubusercontent.com/7113033/51669507-ec4c8680-1fc4-11e9-8512-4aea838a58ce.png)

Without languages;
![2019-01-24 10_40_40-window](https://user-images.githubusercontent.com/7113033/51669524-f3739480-1fc4-11e9-9b0e-09df373a5140.png)

**Comment by iJungleboy** [comment]
ok. I'll relabel the issue.

**Comment by iJungleboy** [comment]
Thx. BTW: whenever you close issues, please also add 1-3 Screenshots showing the result.

**Comment by PagnoDunadan** [comment]
**All languages fit:**
![noshadows](https://user-images.githubusercontent.com/7113033/52039531-135f0700-2535-11e9-8e8c-1633e844b86e.png)

**Right side can't fit:**
![rightshadow](https://user-images.githubusercontent.com/7113033/52039565-25d94080-2535-11e9-9e97-44c27264abd7.png)

**Left side can't fit:**
![leftshadow](https://user-images.githubusercontent.com/7113033/52039613-486b5980-2535-11e9-8325-4267df0e9346.png)

**Neither side can fit:**
![bothshadows](https://user-images.githubusercontent.com/7113033/52039624-528d5800-2535-11e9-8c6d-37601fce996e.png)

White shadows are calculated on scroll and on window resize. On click, selected language moves to the center and language switcher is scrollable.
