### ISSUE TITLE
Finish field-level language-translation-state indicators

### ISSUE THREAD

**Issue by iJungleboy** [2sic/eav-item-dialog-angular#48]
## I'm submitting a ...

[x] action / task

## ...about

[x] edit experience / UI

### Icon-Indicator (new)

1.	The icon indicator is only visible on secondary languages, so not on the first/primary language.
2.	In most modes it is the default color, as in most modes, the user doesn’t need to be aware of anything special going on.
    1.	Not used at all (not editable) – the user can’t do anything wrong
    2.	Share read (not editable) – the user can’t break anything
    3.	De-coupled (editable / translate, this language only) – common case, the user break anything
3.	If it is a special share-mode (share read or share read/write) it must have a different color to better indicate that changes will have side-effects. In this case, it should be the secondary color (blue)

### Language-Share Indicator (new)

If the language is in the special share-mode (fairly uncommon) it’s important that the user sees what languages will be affected. For this, the user should see a list of languages in small font within the input-box, according to these specs:
1.	Font-size: same as the small label when a field has content
2.	Font-color: same as the field-label (gray when not focused, secondary (blue) when focused)
3.	Alignment & spacing: top-right, distance from borders same as the “real” label to the top-left
4.	Text to show: same as in the old 2sxc, a combination of language-codes and share-mode-codes

## Steps to implement

* [x] Implement icon behavior
* [x] Implement label-behavior

**Comment by PagnoDunadan** [comment]
**Default:**

![default](https://user-images.githubusercontent.com/7113033/52399633-1b7eef80-2abd-11e9-8173-9100ea9cd0a0.png)

**Translate:**

![translate](https://user-images.githubusercontent.com/7113033/52399649-22a5fd80-2abd-11e9-9838-0117a459bd2e.png)

**Shared:**

![shared](https://user-images.githubusercontent.com/7113033/52399657-289bde80-2abd-11e9-954d-75b8c0449c68.png)

**Comment by PagnoDunadan** [comment]
Shared languages indicator now shows shorter names and excludes current language.

**Read-write:**
![2019-02-14 13_13_56-2sxc-dnn742 _ testeditui](https://user-images.githubusercontent.com/7113033/52786299-cf065780-305a-11e9-9820-24acbd197acd.png)

**Read only:**
![2019-02-14 13_14_06-2sxc-dnn742 _ testeditui](https://user-images.githubusercontent.com/7113033/52786300-d0d01b00-305a-11e9-8b42-02348a3f9073.png)
