### ISSUE TITLE
Use title from url for the edit-cards

### ISSUE THREAD

**Issue by iJungleboy** [2sic/eav-item-dialog-angular#68]
## I'm submitting a ...
[x] action / task

## ...about
[x] edit experience / UI

## Task / Action Summary
The items-data from the server includes header information for each item. That has a "Title" property which should be used for the cards (currently Edit Item). Use "Edit Item" only if no title provided.
![image](https://user-images.githubusercontent.com/5321186/57540098-30814e00-734c-11e9-9981-600cf8eaa679.png)

**Comment by PagnoDunadan** [comment]
![2019-05-22 10_40_43-My Website _ testing edit ui](https://user-images.githubusercontent.com/7113033/58160126-22053180-7c7e-11e9-81ba-140794601fa0.png)
