### ISSUE TITLE
bug: Entity list refreshed to late when parameters change

### ISSUE THREAD

**Issue by iJungleboy** [2sic/eav-item-dialog-angular#78]
In the view-editor, we have this situation

1. a dropdown picks the content type
1. another dropdown offers the items for that type

When I select a new content-type, a request is sent immediately to the server to get the items. This is correct. BUT when I then open the item-picker, there is a delay - the first open still shows me items of the previously selected type. Only when I click again, does the list get changed to show the correct items.

**pls look at in the afternoon**

**Comment by PagnoDunadan** [comment]
Entity picker in view configuration doesn't resolve mask when trying to create a new entity

![2019-05-24 11_36_11-Window](https://user-images.githubusercontent.com/7113033/58318575-501e7900-7e18-11e9-91fd-5391caef0bf7.png)
