### ISSUE TITLE
Can't upload to subfolders and in image manager

### ISSUE THREAD

**Issue by PagnoDunadan** [2sic/eav-item-dialog-angular#84]
## I'm submitting a ...

[x] action / task

## ...about

[x] edit experience / UI

## Task / Action Summary
Fix uploading in Adam (usePortalRoot = false) and it's subfolders and Image manager (usePortalRoot = true) and it's subfolders

**Comment by iJungleboy** [comment]
I think this is done, right?

**Comment by PagnoDunadan** [comment]
Yep. Implemented and tested. Closing
