### ISSUE TITLE
WYSIWYG preview isn't updated when text is added

### ISSUE THREAD

**Issue by iJungleboy** [2sic/eav-item-dialog-angular#87]
I just added some wysiwyg text, and pressing back still showed an empty wysiwyg. Not sure why, but the preview doesn't seem to update reliably.

**Comment by PagnoDunadan** [comment]
Fixed in [this commit](https://github.com/2sic/eav-item-dialog-angular/commit/3d05a4d670cc7f658035cc62bef8bf80674613e8).
